#!/usr/bin/env ruby

require 'topicz'

begin
  command = Topicz.create_command
  if command != nil
    command.execute
    exit 0
  else
    puts 'Invalid command. Try topicz --help'
    exit -1
  end
rescue Exception => e
  if e.message != 'exit'
    puts e.message
    exit -1
  end
end

