#!/usr/bin/env ruby

require 'topicz/application'

begin
  Topicz::Application.new.run
rescue Exception => e
  if e.message != 'exit' # There's probably a better way to do this...
    puts e.message
    exit -1
  end
end
